export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const PROFILE_LOAD = 'PROFILE_LOAD';
export const PROFILE_CLEAR = 'PROFILE_CLEAR';
export const PROFILE_TRY_TO_LOAD = 'PROFILE_TRY_TO_LOAD';

export const REG_REQUEST = 'REG_REQUEST';

export const TOPIC_LOAD = 'TOPIC_LOAD';
export const TOPIC_CLEAR = 'TOPIC_CLEAR';
export const TOPIC_ADD_COMMENT = 'TOPIC_ADD_COMMENT';
export const TOPIC_UPD_COMMENT = 'TOPIC_UPD_COMMENT';
export const TOPIC_DELETE = 'TOPIC_DELETE';
export const TOPIC_DEL_COMMENT = 'TOPIC_DEL_COMMENT'
